# First run
# echo HOST_ADDR=$(curl -s https://api.ipify.org) > .env && docker-compose up -d && docker-compose exec -d dockovpn wget -O /doc/Dockovpn/client.ovpn localhost:8080

version: '3'
services:
  dockovpn:
    image: alekslitvinenk/openvpn
    container_name: dockovpn
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
      - "80:8080/tcp"
    restart: unless-stopped
      #stdin_open: true # equivalent to -i in docker run
      #tty: true        # equivalent to -t in docker run

